# Generated by Django 6.0.6 on 2026-08-15 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('decoration', 'Decoration'), ('food_veg', 'Food - Veg'), ('food_nonveg', 'Food - Non-Veg'), ('photography', 'Photography')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='services/')),
                ('description', models.TextField(blank=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='venues.venue')),
            ],
        ),
    ]
