# Generated by Django 6.0.6 on 2026-08-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0009_venueservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='venues.venueservice'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
